// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pvm.Infrastructure.Persistence;

#nullable disable

namespace Pvm.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(PvmDbContext))]
    [Migration("20260806133516_AddAcumaticaReconciliationCursors")]
    partial class AddAcumaticaReconciliationCursors
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Pvm.Infrastructure.Persistence.Entities.AppUserAuditEventEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid?>("ActorAppUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("AfterJson")
                        .HasColumnType("jsonb");

                    b.Property<string>("BeforeJson")
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("TargetAppUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ActorAppUserId");

                    b.HasIndex("TargetAppUserId");

                    b.ToTable("app_user_audit_events", (string)null);
                });

            modelBuilder.Entity("Pvm.Infrastructure.Persistence.Entities.AppUserEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<string>("EntraObjectId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("EntraObjectId")
                        .IsUnique();

                    b.ToTable("app_users", (string)null);
                });

            modelBuilder.Entity("Pvm.Infrastructure.Persistence.Entities.AppUserRoleEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AppUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("GrantedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("GrantedByAppUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("GrantedByAppUserId");

                    b.HasIndex("AppUserId", "Role")
                        .IsUnique();

                    b.ToTable("app_user_roles", (string)null);
                });

            modelBuilder.Entity("Pvm.Infrastructure.Persistence.Entities.AuditEventEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Actor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DetailsJson")
                        .HasColumnType("text");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("EntityType", "EntityId");

                    b.ToTable("audit_events", (string)null);
                });

            modelBuilder.Entity("Pvm.Infrastructure.Persistence.Entities.IntegrationMessageDeliveryEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CausationId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("DeadLetterReason")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("DeliveryCount")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("EnqueuedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ErrorSummary")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<DateTimeOffset>("FirstReceivedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("LastReceivedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MessageId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("QueueName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CorrelationId");

                    b.HasIndex("QueueName", "MessageId")
                        .IsUnique();

                    b.HasIndex("Status", "UpdatedAt");

                    b.ToTable("integration_message_deliveries", (string)null);
                });

            modelBuilder.Entity("Pvm.Infrastructure.Persistence.Entities.IntegrationOutboxMessageEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("AvailableAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CausationId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastErrorCode")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("LastErrorSummary")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<DateTimeOffset?>("LeaseExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("LeaseId")
                        .HasColumnType("uuid");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("PublishAttempts")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("QueueName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CorrelationId");

                    b.HasIndex("Status", "AvailableAt");

                    b.ToTable("integration_outbox_messages", (string)null);
                });

            modelBuilder.Entity("Pvm.Infrastructure.Persistence.Entities.IntegrationRunEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CreatedCount")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("CursorAfter")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("CursorBefore")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EnvironmentName")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ErrorSummary")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<int>("FailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("InitiatedBy")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<Guid?>("MessageId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("QueryFrom")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("QueryTo")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ReceivedCount")
                        .HasColumnType("integer");

                    b.Property<int>("RevalidatedCount")
                        .HasColumnType("integer");

                    b.Property<string>("RunType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ScheduleKey")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("SkippedCount")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Trigger")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("UnchangedCount")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UpdatedCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CorrelationId");

                    b.HasIndex("ScheduleKey")
                        .IsUnique()
                        .HasFilter("\"ScheduleKey\" IS NOT NULL");

                    b.HasIndex("RunType", "CursorAfter");

                    b.HasIndex("RunType", "Status", "UpdatedAt");

                    b.ToTable("integration_runs", (string)null);
                });

            modelBuilder.Entity("Pvm.Infrastructure.Persistence.Entities.InvoiceCandidateEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AcumaticaInvoiceId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CanonicalJson")
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CustomerAccount")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CustomerLocation")
                        .HasColumnType("text");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("InvoiceNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("MatchedShopritePurchaseOrderId")
                        .HasColumnType("uuid");

                    b.Property<string>("ShopritePurchaseOrderNumber")
                        .HasColumnType("text");

                    b.Property<string>("SourceJson")
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset?>("SourceLastModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("StoreDcGln")
                        .HasColumnType("text");

                    b.Property<string>("SupplierGln")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ValidationJson")
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique();

                    b.HasIndex("MatchedShopritePurchaseOrderId");

                    b.ToTable("invoice_candidates", (string)null);
                });

            modelBuilder.Entity("Pvm.Infrastructure.Persistence.Entities.InvoiceSubmissionAttemptEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text");

                    b.Property<string>("FailureClassification")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("InitiatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("InitiationMode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("InvoiceCandidateId")
                        .HasColumnType("uuid");

                    b.Property<bool?>("IsRetryEligible")
                        .HasColumnType("boolean");

                    b.Property<string>("RecommendedFixLocation")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("RequestPayload")
                        .HasColumnType("text");

                    b.Property<string>("RequestPayloadHash")
                        .HasColumnType("text");

                    b.Property<string>("RequestPayloadLocation")
                        .HasColumnType("text");

                    b.Property<string>("ResponsePayload")
                        .HasColumnType("text");

                    b.Property<string>("ResponsePayloadHash")
                        .HasColumnType("text");

                    b.Property<string>("ResponsePayloadLocation")
                        .HasColumnType("text");

                    b.Property<int?>("ResponseStatusCode")
                        .HasColumnType("integer");

                    b.Property<string>("ResponsibleRole")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid?>("SubmissionOperationId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceCandidateId");

                    b.HasIndex("SubmissionOperationId")
                        .IsUnique()
                        .HasFilter("\"SubmissionOperationId\" IS NOT NULL");

                    b.ToTable("invoice_submission_attempts", (string)null);
                });

            modelBuilder.Entity("Pvm.Infrastructure.Persistence.Entities.PayloadArchiveEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<long>("ByteCount")
                        .HasColumnType("bigint");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("InvoiceCandidateId")
                        .HasColumnType("uuid");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<string>("Sha256Hash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("SubmissionOperationId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceCandidateId");

                    b.HasIndex("SubmissionOperationId", "Kind")
                        .IsUnique();

                    b.ToTable("payload_archives", (string)null);
                });

            modelBuilder.Entity("Pvm.Infrastructure.Persistence.Entities.ShopriteItemMappingEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AcumaticaInventoryId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Gtin")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("boolean");

                    b.Property<string>("ShopriteBuyerItemId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.HasKey("Id");

                    b.HasIndex("AcumaticaInventoryId", "ShopriteBuyerItemId")
                        .IsUnique();

                    b.ToTable("shoprite_item_mappings", (string)null);
                });

            modelBuilder.Entity("Pvm.Infrastructure.Persistence.Entities.ShopritePurchaseOrderEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BuyerGln")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("CurrencyCode")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<string>("DeliveryGln")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("DeliveryLocationCode")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("DeliveryLocationName")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("DeliveryLocationSource")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("FirstSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("LastSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OrderHeaderId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("OrderTypeCode")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("OrderTypeLabel")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("PayloadHash")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("PurchaseOrderNumber")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("RawOrderJson")
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset?>("ShopriteCreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ShopriteLastUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SourceEndpoint")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("SourceEnvironment")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("SupplierGln")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<decimal?>("TotalExcludingTax")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("TotalIncludingTax")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("TotalTax")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("DeliveryGln");

                    b.HasIndex("PurchaseOrderNumber")
                        .IsUnique();

                    b.ToTable("shoprite_purchase_orders", (string)null);
                });

            modelBuilder.Entity("Pvm.Infrastructure.Persistence.Entities.ShopritePurchaseOrderLineEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BuyerItemDescription")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("BuyerItemId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Description")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("Gtin")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("LineNumber")
                        .HasColumnType("integer");

                    b.Property<string>("MeasurementUnitCode")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<decimal?>("MonetaryAmountExcludingTaxes")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("MonetaryAmountIncludingTaxes")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("NetAmount")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("NetPrice")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("RequestedQuantity")
                        .HasColumnType("numeric");

                    b.Property<Guid>("ShopritePurchaseOrderId")
                        .HasColumnType("uuid");

                    b.Property<string>("SupplierItemId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.HasIndex("Gtin");

                    b.HasIndex("ShopritePurchaseOrderId", "LineNumber")
                        .IsUnique();

                    b.ToTable("shoprite_purchase_order_lines", (string)null);
                });

            modelBuilder.Entity("Pvm.Infrastructure.Persistence.Entities.ShopriteUomMappingEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AcumaticaInventoryId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("AcumaticaUom")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("boolean");

                    b.Property<string>("ShopriteUom")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.HasKey("Id");

                    b.HasIndex("AcumaticaInventoryId", "AcumaticaUom")
                        .IsUnique();

                    b.ToTable("shoprite_uom_mappings", (string)null);
                });

            modelBuilder.Entity("Pvm.Infrastructure.Persistence.Entities.SubmissionOperationEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CommandId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text");

                    b.Property<string>("FailureClassification")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("FrozenCanonicalJson")
                        .HasColumnType("jsonb");

                    b.Property<string>("FrozenSourceJson")
                        .HasColumnType("jsonb");

                    b.Property<int>("Generation")
                        .HasColumnType("integer");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("InitiatedBy")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<string>("InitiationMode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("InvoiceCandidateId")
                        .HasColumnType("uuid");

                    b.Property<string>("RequestPayload")
                        .HasColumnType("text");

                    b.Property<string>("RequestPayloadHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ResponsePayload")
                        .HasColumnType("text");

                    b.Property<string>("ResponsePayloadHash")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int?>("ResponseStatusCode")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("SendingStartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SourceVersion")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("CommandId")
                        .IsUnique();

                    b.HasIndex("InvoiceCandidateId")
                        .IsUnique()
                        .HasFilter("\"Status\" IN ('Pending', 'Sending', 'Submitted', 'Ambiguous')");

                    b.HasIndex("InvoiceCandidateId", "Generation")
                        .IsUnique();

                    b.HasIndex("Status", "SendingStartedAt");

                    b.ToTable("submission_operations", (string)null);
                });

            modelBuilder.Entity("Pvm.Infrastructure.Persistence.Entities.SubmissionOperationTransitionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Actor")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("InvoiceCandidateId")
                        .HasColumnType("uuid");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("NewState")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("PayloadHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("PreviousState")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("SourceVersion")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid>("SubmissionOperationId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceCandidateId", "CreatedAt");

                    b.HasIndex("SubmissionOperationId", "CreatedAt");

                    b.ToTable("submission_operation_transitions", (string)null);
                });

            modelBuilder.Entity("Pvm.Infrastructure.Persistence.Entities.AppUserAuditEventEntity", b =>
                {
                    b.HasOne("Pvm.Infrastructure.Persistence.Entities.AppUserEntity", null)
                        .WithMany()
                        .HasForeignKey("ActorAppUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Pvm.Infrastructure.Persistence.Entities.AppUserEntity", null)
                        .WithMany()
                        .HasForeignKey("TargetAppUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Pvm.Infrastructure.Persistence.Entities.AppUserRoleEntity", b =>
                {
                    b.HasOne("Pvm.Infrastructure.Persistence.Entities.AppUserEntity", null)
                        .WithMany()
                        .HasForeignKey("AppUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Pvm.Infrastructure.Persistence.Entities.AppUserEntity", null)
                        .WithMany()
                        .HasForeignKey("GrantedByAppUserId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("Pvm.Infrastructure.Persistence.Entities.InvoiceCandidateEntity", b =>
                {
                    b.HasOne("Pvm.Infrastructure.Persistence.Entities.ShopritePurchaseOrderEntity", null)
                        .WithMany()
                        .HasForeignKey("MatchedShopritePurchaseOrderId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("Pvm.Infrastructure.Persistence.Entities.InvoiceSubmissionAttemptEntity", b =>
                {
                    b.HasOne("Pvm.Infrastructure.Persistence.Entities.InvoiceCandidateEntity", null)
                        .WithMany()
                        .HasForeignKey("InvoiceCandidateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Pvm.Infrastructure.Persistence.Entities.PayloadArchiveEntity", b =>
                {
                    b.HasOne("Pvm.Infrastructure.Persistence.Entities.InvoiceCandidateEntity", null)
                        .WithMany()
                        .HasForeignKey("InvoiceCandidateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Pvm.Infrastructure.Persistence.Entities.SubmissionOperationEntity", null)
                        .WithMany("PayloadArchives")
                        .HasForeignKey("SubmissionOperationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Pvm.Infrastructure.Persistence.Entities.ShopritePurchaseOrderLineEntity", b =>
                {
                    b.HasOne("Pvm.Infrastructure.Persistence.Entities.ShopritePurchaseOrderEntity", null)
                        .WithMany("Lines")
                        .HasForeignKey("ShopritePurchaseOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Pvm.Infrastructure.Persistence.Entities.SubmissionOperationEntity", b =>
                {
                    b.HasOne("Pvm.Infrastructure.Persistence.Entities.InvoiceCandidateEntity", null)
                        .WithMany()
                        .HasForeignKey("InvoiceCandidateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Pvm.Infrastructure.Persistence.Entities.SubmissionOperationTransitionEntity", b =>
                {
                    b.HasOne("Pvm.Infrastructure.Persistence.Entities.InvoiceCandidateEntity", null)
                        .WithMany()
                        .HasForeignKey("InvoiceCandidateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Pvm.Infrastructure.Persistence.Entities.SubmissionOperationEntity", null)
                        .WithMany()
                        .HasForeignKey("SubmissionOperationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Pvm.Infrastructure.Persistence.Entities.ShopritePurchaseOrderEntity", b =>
                {
                    b.Navigation("Lines");
                });

            modelBuilder.Entity("Pvm.Infrastructure.Persistence.Entities.SubmissionOperationEntity", b =>
                {
                    b.Navigation("PayloadArchives");
                });
#pragma warning restore 612, 618
        }
    }
}
